package experimental_test

import (
	"context"
	_ "embed"
	"errors"
	"fmt"
	"log"

	"github.com/tetratelabs/wazero"
	"github.com/tetratelabs/wazero/experimental"
)

// fuelWasm was generated by the following:
//
//	cd testdata; wat2wasm fuel.wat
//
//go:embed testdata/fuel.wasm
var fuelWasm []byte

// ExampleSetFuel shows how to bound a WebAssembly module's CPU consumption
// using the experimental fuel API: each dispatched wasm operation consumes
// one unit, and execution traps with ErrOutOfFuel when the budget reaches
// zero. SetFuel both installs the initial budget and refuels mid-execution.
func ExampleSetFuel() {
	ctx := context.Background()

	// Fuel is honored only by the interpreter engine.
	r := wazero.NewRuntimeWithConfig(ctx, wazero.NewRuntimeConfigInterpreter())
	defer r.Close(ctx)

	mod, err := r.Instantiate(ctx, fuelWasm)
	if err != nil {
		log.Panicln(err)
	}
	add := mod.ExportedFunction("add")

	// Install a budget on ctx. SetFuel returns a new ctx the first time it
	// is called; later SetFuel calls on the same ctx mutate the meter in
	// place.
	ctx = experimental.SetFuel(ctx, 100)

	// Call with plenty of fuel.
	if _, err = add.Call(ctx, 2, 3); err != nil {
		log.Panicln(err)
	}
	if experimental.GetFuel(ctx) < 100 {
		fmt.Println("call 1: completed, fuel consumed")
	}

	// Refuel to a budget too small to cover the next call.
	experimental.SetFuel(ctx, 1)
	if _, err = add.Call(ctx, 4, 5); errors.Is(err, experimental.ErrOutOfFuel) {
		fmt.Println("call 2: out of fuel")
	}

	// Refuel and run again.
	experimental.SetFuel(ctx, 100)
	res, err := add.Call(ctx, 4, 5)
	if err != nil {
		log.Panicln(err)
	}
	fmt.Printf("call 3: result=%d\n", res[0])

	// Output:
	// call 1: completed, fuel consumed
	// call 2: out of fuel
	// call 3: result=9
}
